### ISSUE TITLE
一点翻译建议

### ISSUE THREAD

**Issue by hebrewsnabla** [Mulliken/szaboqc#1]
提一点建议。
1.  人名不翻译可以理解，但是Hamiltonian应该翻译成哈密顿量，Hermitian应该翻译成厄米(的)——这俩又不是纯人名。我注意到有一些章节写的是“厄米”，有一些章节出现了“Hamilton量”，应该统一一下。
2.  3.4.7节，“布局分析”应为“布居分析”。另，脚注当中说译为“布局分解”比较好，我不明白这是什么意思。一来analysis并无分解的意思，二来如果要表示分解应该用decomposition。这里译成“布居分析”应该是一个公认的译法。
3.  3.4.6节，Procedure应该译为“流程”，或“步骤”，而不是“手续”。

**Comment by Mulliken** [comment]
谢谢 Shirong 非常有用的建议！非常正确，这些术语翻译时应当统一，我之后会全部改掉。

关于布居分解这个译法，我的考虑是这样的。我们在说分析这个词时，第一个想到的意思是“你给我分析分析这个事情；数学分析；时事分析” 这些词句中的那种分析，而非 “条分缕析；分崩离析” 中的分析。当然这两者的意味挨得相当近，但对我来说，布居分析中的分析似乎更靠近后者，而后者中的分析实际上就是分解。若用分解，则意思相当明确，就是将总的电子数目分配到各个原子上去。更有一点， analysis 的词根 lysis 直接就是解开的意思。这是我的一孔之见。

关于 Procedure 这个词的译法，我在翻译过程有时愿意用一些朴实的词汇，而不是更显现代的词。这纯粹是个人“陋习”了。

非常感谢 Shirong 的建议和想法，这些都是个人想法，请批评。

**Comment by Mulliken** [comment]
我又想了想布居分析的英文词 Population Analysis。的确，Population似指某个区域的人口，在化学中，这个“地方”就是原子。如此说来，确实布居分析更合适，因为我们在分析每个原子上的占据情况，若写成布居分解，似乎暗示我们把每个原子上的 Population 进一步分解了。谢谢 Shirong 的批评和启发！

**Comment by hebrewsnabla** [comment]
嗯，布居分析的分析就是前者，别想那么复杂。

诸如energy decomposition analysis，charge decomposition analysis中的analysis都是同样的意思。
