### ISSUE TITLE
这个项目现在还有人还做吗？有没有出版中译版的计划？

### ISSUE THREAD

**Issue by DechinPhy** [Mulliken/szaboqc#5]

**Comment by Mulliken** [comment]
Dechin 你好~

@shenyi97 两个月前曾commit过更新。我则在近期没有持续翻译剩余章节的计划。至于出版，版权问题较难解决，因为Dover出版社通常并不授权其他人翻译该社的书（他们自己也不翻译）。

如果你愿意翻译一些章节，非常欢迎~
