### ISSUE TITLE
关于仓库体积过大的问题

### ISSUE THREAD

**Issue by hebrewsnabla** [Mulliken/szaboqc#9]
由于现在把main.pdf放在代码里面，每commit一次，就会增加一个main.pdf的体积。所以现在clone项目时整体体积已经比较大了。

我觉得可以把pdf从仓库中移除，放到release里面（每次往master merge一些修改的时候就release一次）。

**Comment by Mulliken** [comment]
同意，频繁修改的 pdf 文件不适合被 git 跟踪。

**Comment by Mulliken** [comment]
你介意做一下这个事情吗？我这两天有点懒，不想研究自动 release 的事情。或者等我这周末研究一下。

**Comment by hebrewsnabla** [comment]
我的本意是手动release :rofl: 自动的我也可以研究一下

**Comment by hebrewsnabla** [comment]
搞定了。你看看release里面自动编译的szabo_zh-v*.pdf有没有问题？

**Comment by Mulliken** [comment]
没问题了! 感谢 @hebrewsnabla 😋
